In [3]:
import pymongo
import pandas as pd
import pickle
import datetime
import time
import gzip
import lzma
import pytz


def DB(host, db_name, user, passwd):
    auth_db = db_name if user not in ('admin', 'root') else 'admin'
    uri = 'mongodb://%s:%s@%s/?authSource=%s' % (user, passwd, host, auth_db)
    return DBObj(uri, db_name=db_name)


class DBObj(object):
    def __init__(self, uri, symbol_column='skey', db_name='white_db'):
        self.db_name = db_name
        self.uri = uri
        self.client = pymongo.MongoClient(self.uri)
        self.db = self.client[self.db_name]
        self.chunk_size = 20000
        self.symbol_column = symbol_column
        self.date_column = 'date'

    def parse_uri(self, uri):
        # mongodb://user:password@example.com
        return uri.strip().replace('mongodb://', '').strip('/').replace(':', ' ').replace('@', ' ').split(' ')

    def drop_table(self, table_name):
        self.db.drop_collection(table_name)

    def rename_table(self, old_table, new_table):
        self.db[old_table].rename(new_table)

    def write(self, table_name, df):
        if len(df) == 0: return

        multi_date = False

        if self.date_column in df.columns:
            date = str(df.head(1)[self.date_column].iloc[0])
            multi_date = len(df[self.date_column].unique()) > 1
        else:
            raise Exception('DataFrame should contain date column')

        collection = self.db[table_name]
        collection.create_index([('date', pymongo.ASCENDING), ('symbol', pymongo.ASCENDING)], background=True)
        collection.create_index([('symbol', pymongo.ASCENDING), ('date', pymongo.ASCENDING)], background=True)

        if multi_date:
            for (date, symbol), sub_df in df.groupby([self.date_column, self.symbol_column]):
                date = str(date)
                symbol = int(symbol)
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)
        else:
            for symbol, sub_df in df.groupby([self.symbol_column]):
                collection.delete_many({'date': date, 'symbol': symbol})
                self.write_single(collection, date, symbol, sub_df)

    def write_single(self, collection, date, symbol, df):
        for start in range(0, len(df), self.chunk_size):
            end = min(start + self.chunk_size, len(df))
            df_seg = df[start:end]
            version = 1
            seg = {'ver': version, 'data': self.ser(df_seg, version), 'date': date, 'symbol': symbol, 'start': start}
            collection.insert_one(seg)

    def build_query(self, start_date=None, end_date=None, symbol=None):
        query = {}

        def parse_date(x):
            if type(x) == str:
                if len(x) != 8:
                    raise Exception("`date` must be YYYYMMDD format")
                return x
            elif type(x) == datetime.datetime or type(x) == datetime.date:
                return x.strftime("%Y%m%d")
            elif type(x) == int:
                return parse_date(str(x))
            else:
                raise Exception("invalid `date` type: " + str(type(x)))

        if start_date is not None or end_date is not None:
            query['date'] = {}
            if start_date is not None:
                query['date']['$gte'] = parse_date(start_date)
            if end_date is not None:
                query['date']['$lte'] = parse_date(end_date)

        def parse_symbol(x):
            if type(x) == int:
                return x
            else:
                return int(x)

        if symbol:
            if type(symbol) == list or type(symbol) == tuple:
                query['symbol'] = {'$in': [parse_symbol(x) for x in symbol]}
            else:
                query['symbol'] = parse_symbol(symbol)

        return query

    def delete(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot delete the whole table')
            return None

        collection.delete_many(query)

    def read(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]

        query = self.build_query(start_date, end_date, symbol)
        if not query:
            print('cannot read the whole table')
            return None

        segs = []
        for x in collection.find(query):
            x['data'] = self.deser(x['data'], x['ver'])
            segs.append(x)
        segs.sort(key=lambda x: (x['symbol'], x['date'], x['start']))
        return pd.concat([x['data'] for x in segs], ignore_index=True) if segs else None

    def list_tables(self):
        return self.db.collection_names()

    def list_dates(self, table_name, start_date=None, end_date=None, symbol=None):
        collection = self.db[table_name]
        dates = set()
        if start_date is None:
            start_date = '00000000'
        if end_date is None:
            end_date = '99999999'
        for x in collection.find(self.build_query(start_date, end_date, symbol), {"date": 1, '_id': 0}):
            dates.add(x['date'])
        return sorted(list(dates))

    def ser(self, s, version):
        pickle_protocol = 4
        if version == 1:
            return gzip.compress(pickle.dumps(s, protocol=pickle_protocol), compresslevel=2)
        elif version == 2:
            return lzma.compress(pickle.dumps(s, protocol=pickle_protocol), preset=1)
        else:
            raise Exception('unknown version')

    def deser(self, s, version):
        def unpickle(s):
            return pickle.loads(s)

        if version == 1:
            return unpickle(gzip.decompress(s))
        elif version == 2:
            return unpickle(lzma.decompress(s))
        else:
            raise Exception('unknown version')


def patch_pandas_pickle():
    if pd.__version__ < '0.24':
        import sys
        from types import ModuleType
        from pandas.core.internals import BlockManager
        pkg_name = 'pandas.core.internals.managers'
        if pkg_name not in sys.modules:
            m = ModuleType(pkg_name)
            m.BlockManager = BlockManager
            sys.modules[pkg_name] = m
patch_pandas_pickle()




import pandas as pd
import random
import numpy as np
import glob
import os
import pickle
import datetime
import time
pd.set_option("max_columns", 200)

startTm = datetime.datetime.now()
readPath = '/mnt/Kevin_zhenyu/day_stock/***'
dataPathLs = np.array(glob.glob(readPath))
dataPathLs = dataPathLs[[np.array([os.path.basename(i).split('.')[0][:2] == 'SZ' for i in dataPathLs])]]
db = pd.DataFrame()
for p in dataPathLs:
    dayData = pd.read_csv(p, compression='gzip')
    db = pd.concat([db, dayData])
print(datetime.datetime.now() - startTm)

startDate = '20170101'
endDate = '20170228'
readPath = '/mnt/SZ/***/TickAB/SZ/***'
dataPathLs = np.array(glob.glob(readPath))
dateLs = np.array([os.path.basename(i) for i in dataPathLs])
dataPathLs = dataPathLs[(dateLs >= startDate) & (dateLs <= endDate)]
wr_ong = []
mi_ss = []
dateLs = np.sort(np.unique([os.path.basename(i) for i in dataPathLs]))

for date in dateLs:
    
    readPath = '/mnt/SZ/***/TickAB/SZ/' + date + '/***'
    dataPathLs = np.array(glob.glob(readPath))
    dateLs = np.array([int(os.path.basename(i).split('.')[0]) for i in dataPathLs])
    dataPathLs = dataPathLs[(dateLs < 4000) | ((dateLs > 300000) & (dateLs < 310000))]
    SZ = []
    ll = []
    startTm = datetime.datetime.now()
    for i in dataPathLs:
        try:
            df = pd.read_csv(i)
        except:
            print("empty data")
            print(i)
            ll.append(int(os.path.basename(i).split('.')[0]))
            continue
        SZ += [df]
    del df
    SZ = pd.concat(SZ).reset_index(drop=True)
    print(datetime.datetime.now() - startTm)
    
    startTm = datetime.datetime.now()
    SZ["skey"] = SZ["WindCode"].apply(lambda x: int(x.split('.')[0])) + 2000000
    SZ.drop(["WindCode"],axis=1,inplace=True)
    SZ['clockAtArrival'] = SZ['Time'] + SZ['Date'] * 1000000000
    SZ['clockAtArrival'] = SZ["clockAtArrival"].astype(str).apply(lambda x: np.int64(datetime.datetime.strptime(x, '%Y%m%d%H%M%S%f').timestamp()*1e6))
    SZ['datetime'] = SZ["clockAtArrival"].apply(lambda x: datetime.datetime.fromtimestamp(x/1e6))
    SZ["Time"] = SZ['Time'] * 1000
    SZ = SZ.rename(columns={'Time': 'time', 'Date':'date'})
    print(datetime.datetime.now() - startTm)
    
    startTm = datetime.datetime.now()
    SZ["AskPrice"] = SZ["AskPrice"].apply(lambda x: [int(i) for i in x[:-1].split(';')])
    SZ["AskVolume"] = SZ["AskVolume"].apply(lambda x: [int(i) for i in x[:-1].split(';')])
    SZ["BidPrice"] = SZ["BidPrice"].apply(lambda x: [int(i) for i in x[:-1].split(';')])
    SZ["BidVolume"] = SZ["BidVolume"].apply(lambda x: [int(i) for i in x[:-1].split(';')])

    for i in range(1, 11):
        SZ["bid" + str(i) + 'p'] = SZ["BidPrice"].apply(lambda x: x[i-1]/10000)
    SZ.drop(["BidPrice"],axis=1,inplace=True)
    print("1")
    for i in range(1, 11):
        SZ["ask" + str(i) + 'p'] = SZ["AskPrice"].apply(lambda x: x[i-1]/10000)
    SZ.drop(["AskPrice"],axis=1,inplace=True)
    print("2")
    for i in range(1, 11):
        SZ["bid" + str(i) + 'q'] = SZ["BidVolume"].apply(lambda x: x[i-1])
    SZ.drop(["BidVolume"],axis=1,inplace=True)
    print("3")
    for i in range(1, 11):
        SZ["ask" + str(i) + 'q'] = SZ["AskVolume"].apply(lambda x: x[i-1])
    SZ.drop(["AskVolume"],axis=1,inplace=True)
    print("4")
    
    SZ = SZ.fillna(0)
    SZ["ordering"] = SZ.groupby("skey").cumcount()
    SZ["ordering"] = SZ["ordering"] + 1
    SZ['has_missing'] = 0

    for cols in ['Price', 'High', 'Low', 'Open', 'PreClose']:
        SZ[cols] = SZ[cols] / 10000
    SZ = SZ.rename(columns={'Price':'close', 'High':'high', 'Low':'low', 'Open':'open', 'PreClose':'prev_close', 'AccVolume':'cum_volume',
                           'AccTurover':'cum_amount', 'MatchItems':'cum_trades_cnt'})
    
    for col in ["skey", "date", "cum_trades_cnt", "ordering"]:
        SZ[col] = SZ[col].astype('int32')
        
    assert(sum(SZ[SZ["open"] != 0].groupby("skey")["open"].nunique() != 1) == 0)
    assert(sum(SZ[SZ["prev_close"] != 0].groupby("skey")["prev_close"].nunique() != 1) == 0)
    SZ["prev_close"] = np.where(SZ["time"] >= 91500000000, SZ.groupby("skey")["prev_close"].transform("max"), SZ["prev_close"]) 
    SZ["open"] = np.where(SZ["cum_volume"] > 0, SZ.groupby("skey")["open"].transform("max"), SZ["open"])
    assert(sum(SZ[SZ["open"] != 0].groupby("skey")["open"].nunique() != 1) == 0)
    assert(sum(SZ[SZ["prev_close"] != 0].groupby("skey")["prev_close"].nunique() != 1) == 0)
    assert(SZ[SZ["cum_volume"] > 0]["open"].min() > 0)
    
    print(datetime.datetime.now() - startTm)
    
    
    # check 1
    startTm = datetime.datetime.now()
    da_te = str(SZ["date"].iloc[0]) 
    da_te = da_te[:4] + '-' + da_te[4:6] + '-' + da_te[6:8]
    db1 = db[db["date"] == da_te]
    db1["ID"] = db1["ID"].str[2:].astype(int) + 2000000
    db1["date"] = (db1["date"].str[:4] + db1["date"].str[5:7] + db1["date"].str[8:]).astype(int)
    SZ["cum_max"] = SZ.groupby("skey")["cum_volume"].transform(max)
    s2 = SZ[SZ["cum_volume"] == SZ["cum_max"]].groupby("skey").first().reset_index()
    SZ.drop("cum_max", axis=1, inplace=True)
    s2 = s2.rename(columns={"skey": "ID", 'open':"d_open", "prev_close":"d_yclose","high":"d_high", "low":"d_low", 
                            "close":"d_close", "cum_volume":"d_volume", "cum_amount":"d_amount"})
    s2 = s2[["ID", "date", "d_open", "d_yclose", "d_high", "d_low", "d_close", "d_volume", "d_amount"]]
    re = pd.merge(db1, s2, on=["ID", "date", "d_open", "d_yclose","d_high", "d_low", "d_volume"], how="outer")
    try:
        assert(sum(re["d_amount_y"].isnull()) == 0)
    except:
        sl = list(re[re["d_amount_y"].isnull()]['ID'].unique())
        sl.remove(2001872)
        sl.remove(2001914)
        display(db1[db1['ID'].isin(sl)][["ID", "date", "d_open", "d_yclose", "d_high", "d_low", "d_close", "d_volume", "d_amount"]])
        display(s2[s2['ID'].isin(sl)][["ID", "date", "d_open", "d_yclose", "d_high", "d_low", "d_close", "d_volume", "d_amount"]])
        try:
            sl1 = s2[(s2['ID'].isin(sl)) & (s2['d_yclose'] != 0)]['ID'].unique()
            sl2 = s2[(s2['ID'].isin(sl)) & (s2['d_yclose'] == 0)]['ID'].unique()
            assert(s2[s2['ID'].isin(sl)]['d_yclose'].unique() == [0.])
            SZ = pd.merge(SZ, db1[db1['ID'].isin(sl2)][["ID", "date", "d_yclose"]], left_on=['skey', 'date'], right_on=['ID', 'date'],
                         how='left')
            SZ.loc[~SZ['ID'].isnull(), 'prev_close'] = SZ.loc[~SZ['ID'].isnull()]['d_yclose']
            SZ.drop(["ID", "d_yclose"], axis=1, inplace=True)               
        except:
            print('!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Attention!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            wr_ong += [re[re['ID'].isin(sl1)]]
    del re
    del s2
    del db1
    print(datetime.datetime.now() - startTm)
    
    # check 2
    # first part
    startTm = datetime.datetime.now()
    date = pd.DataFrame(pd.date_range(start='2019-06-10 08:30:00', end='2019-06-10 18:00:00', freq='s'), columns=["Orig"])
    date["time"] = date["Orig"].apply(lambda x: int(x.strftime("%H%M%S"))*1000)
    date["group"] = date["time"]//10000
    SZ["group"] = SZ["time"]//10000000
    gl = date[((date["time"] >= 93000000) & (date["time"] <= 113000000))|((date["time"] >= 130000000) & (date["time"] <= 150000000))]["group"].unique()
    l = set(gl) - set(SZ["group"].unique())
    SZ["has_missing1"] = 0 
    if len(l) != 0:
        print("massive missing")
        print(l)
        SZ["order"] = SZ.groupby(["skey", "time"]).cumcount()
        for i in l:
            SZ["t"] = SZ[SZ["group"] > i].groupby("StockID")["time"].transform("min")
            SZ["has_missing1"] = np.where((SZ["time"] == SZ["t"]) & (SZ["order"] == 0), 1, 0)
        SZ.drop(["order", "t", "group"], axis=1, inplace=True)   
    else:
        print("no massive missing")
        SZ.drop(["group"], axis=1, inplace=True)
    
    # second part

    SZ["time_interval"] = SZ.groupby("skey")["datetime"].apply(lambda x: x - x.shift(1))
    SZ["time_interval"] = SZ["time_interval"].apply(lambda x: x.seconds)
    SZ["tn_update"] = SZ.groupby("skey")["cum_trades_cnt"].apply(lambda x: x-x.shift(1))

    f1 = SZ[(SZ["time"] >= 93000000000) & (SZ["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f1 = f1.rename(columns={"time": "time1"})
    f2 = SZ[(SZ["time"] >= 130000000000) & (SZ["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f2 = f2.rename(columns={"time": "time2"})
    f3 = SZ[(SZ["time"] >= 150000000000) & (SZ["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f3 = f3.rename(columns={"time": "time3"})
    f4 = SZ[(SZ["time"] >= 100000000000) & (SZ["tn_update"] != 0)].groupby("skey")["time"].min().reset_index()
    f4 = f4.rename(columns={"time": "time4"})
    SZ = pd.merge(SZ, f1, on="skey", how="left")
    del f1
    SZ = pd.merge(SZ, f2, on="skey", how="left")
    del f2
    SZ = pd.merge(SZ, f3, on="skey", how="left")
    del f3
    SZ = pd.merge(SZ, f4, on="skey", how="left")
    del f4
    stock_list = SZ[(SZ['time'] == SZ['time4']) & (SZ['time_interval'] > 1500)]['skey'].unique()
    display(stock_list)
    SZ.loc[~SZ['skey'].isin(stock_list), 'time4'] = 0
    p99 = SZ[(SZ["time"] > 93000000000) & (SZ["time"] < 145700000000) & (SZ["time"] != SZ["time2"]) & (SZ["tn_update"] != 0)]\
    .groupby("skey")["tn_update"].apply(lambda x: x.describe([0.99])["99%"]).round(0).reset_index()
    p99 = p99.rename(columns={"tn_update":"99%"})
    SZ = pd.merge(SZ, p99, on="skey", how="left")

    SZ["has_missing2"] = 0
    if len(stock_list) == 0:
        SZ["has_missing2"] = np.where((SZ["time_interval"] > 60) & (SZ["tn_update"] > SZ["99%"]) & 
             (SZ["time"] > SZ["time1"]) & (SZ["time"] != SZ["time2"]) & (SZ["time"] != SZ["time3"]), 1, 0)
    else:
        SZ["has_missing2"] = np.where((SZ["time_interval"] > 60) & (SZ["tn_update"] > SZ["99%"]) & 
             (SZ["time"] > SZ["time1"]) & (SZ["time"] != SZ["time2"]) & (SZ["time"] != SZ["time3"]) & 
             (SZ['time'] != SZ['time4']), 1, 0)        
    SZ.drop(["time_interval", "tn_update", "time1", "time2", "time3", "99%"], axis=1, inplace=True) 

    SZ["has_missing"] = np.where((SZ["has_missing1"] == 1) | (SZ["has_missing2"] == 1), 1, 0)
    SZ.drop(["has_missing1", "has_missing2"], axis=1, inplace=True) 
    if SZ[SZ["has_missing"] == 1].shape[0] != 0:
        print("has missing!!!!!!!!!!!!!!!!!!!!!!!")
        print(SZ[SZ["has_missing"] == 1].shape[0])
        mi_ss += [SZ[SZ["has_missing"] == 1]]
    print(datetime.datetime.now() - startTm)

    
    
    startTm = datetime.datetime.now()
    SZ["has_missing"] = SZ["has_missing"].astype('int32')
    SZ = SZ[["skey", "date", "time", "clockAtArrival", "datetime", "ordering", "has_missing", "cum_trades_cnt", "cum_volume", "cum_amount", "prev_close",
                            "open", "high", "low", "close", 'bid10p','bid9p','bid8p','bid7p','bid6p','bid5p','bid4p','bid3p','bid2p','bid1p',
                            'ask1p','ask2p','ask3p','ask4p','ask5p','ask6p','ask7p','ask8p','ask9p','ask10p', 'bid10q','bid9q','bid8q',
                             'bid7q','bid6q','bid5q','bid4q','bid3q','bid2q','bid1q', 'ask1q','ask2q','ask3q','ask4q','ask5q','ask6q',
                             'ask7q','ask8q','ask9q','ask10q']]
    
    display(SZ["date"].iloc[0])
    print("SZ finished")
    
    
    database_name = 'com_md_eq_cn'
    user = "zhenyuy"
    password = "bnONBrzSMGoE"

    db1 = DB("192.168.10.178", database_name, user, password)
    db1.write('md_snapshot_l2', SZ)
    
    del SZ
    print(datetime.datetime.now() - startTm)

wr_ong = pd.concat(wr_ong).reset_index(drop=True)
print(wr_ong)
mi_ss = pd.concat(mi_ss).reset_index(drop=True)
print(mi_ss)    

/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:195: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


0:06:12.201214
0:01:54.381107
0:01:24.545882
1
2
3
4
0:03:16.396974


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
216  2000540  20170103    7.00      6.93    7.47   6.92     7.05  97828693.0   
65   2002071  20170103   15.00     13.64   15.00  14.48    15.00  28852672.0   
122  2002491  20170103   15.89     15.54   16.09  15.50    15.50   9996926.0   
70   2000547  20170103   16.90     15.36   16.90  16.90    16.90   4230192.0   
123  2002059  20170103   11.97     11.95   12.25  11.70    12.08  12013616.0   
143  2002567  20170103   12.75     12.64   12.77  12.05    12.25  11514432.0   

         d_amount  
216  6.965606e+08  
65   4.316069e+08  
122  1.575170e+08  
70   7.149024e+07  
123  1.442012e+08  
143  1.409509e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
133   2000540  20170103    7.00      0.00    7.47   6.92     7.05  97828693   
139   2000547  20170103   16.90      0.00   16.90  16.90    16.90   4230192   
523   2002059  20170103   11.97     11.97   12.25  11.70    12.08  12013616   
535   2002071  20170103   15.00      0.00   15.00  14.48    15.00  28852672   
954   2002491  20170103   15.89      0.00   16.09  15.50    15.50   9996926   
1029  2002567  20170103   12.75      0.00   12.77  12.05    12.25  11514432   

       d_amount  
133   696560629  
139    71490244  
523   144201188  
535   431606895  
954   157516978  
1029  140950866

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Attention!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0:00:03.167536
no massive missing


array([], dtype=int32)

0:01:36.503139


20170103

SZ finished
0:00:28.274405
0:02:06.354458
0:01:30.889562
1
2
3
4
0:03:45.674716


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close     d_volume  \
175  2300243  20170104   16.70     15.18   16.70  16.70    16.70    5763113.0   
116  2000710  20170104   52.15     47.41   52.15  52.15    52.15    1150808.0   
234  2002738  20170104   29.01     26.37   29.01  29.01    29.01     921891.0   
0    2300586  20170104   12.13      9.30   13.39  12.13    13.39       3653.0   
151  2000585  20170104    7.40      7.77    8.55   7.02     8.55   63671177.0   
111  2002297  20170104   13.40     13.09   14.40  13.01    14.40   31663572.0   
242  2000595  20170104   10.97     10.55   11.61  10.44    11.61  118746733.0   
145  2000611  20170104    8.36      7.96    8.36   8.36     8.36     262761.0   

         d_amount  
175  9.624399e+07  
116  6.001464e+07  
234  2.674406e+07  
0    4.882189e+04  
151  5.191826e+08  
111  4.361423e+08  
242  1.308624e+09  
145  2.196682e+06

ID      date  d_open  d_yclose  d_high  d_low  d_close   d_volume  \
166   2000585  20170104    7.40       0.0    8.55   7.02     8.55   63671177   
174   2000595  20170104   10.97       0.0   11.61  10.44    11.61  118746733   
188   2000611  20170104    8.36       0.0    8.36   8.36     8.36     262761   
258   2000710  20170104   52.15       0.0   52.15  52.15    52.15    1150808   
760   2002297  20170104   13.40       0.0   14.40  13.01    14.40   31663572   
1197  2002738  20170104   29.01       0.0   29.01  29.01    29.01     921891   
1527  2300243  20170104   16.70       0.0   16.70  16.70    16.70    5763113   
1856  2300586  20170104   12.13       0.0   13.39  12.13    13.39       3653   

        d_amount  
166    519182620  
174   1308624469  
188      2196681  
258     60014637  
760    436142304  
1197    26744057  
1527    96243987  
1856       48821

0:00:17.693415
no massive missing


array([2300586], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:38.189033


20170104

SZ finished
0:00:31.017450
0:02:18.710540
0:01:34.039545
1
2
3
4
0:03:45.844298


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
179  2002464  20170105   78.03     78.20   78.82  71.00    71.30  10357751.0   
184  2300480  20170105   24.44     22.22   24.44  23.80    24.44   4955837.0   
234  2002408  20170105   11.19     11.00   12.10  11.08    12.10  37026660.0   
0    2300587  20170105   18.62     14.11   20.32  18.62    20.32      8423.0   
241  2002727  20170105   21.66     21.20   21.88  20.84    20.95   7783685.0   
184  2002165  20170105    9.43      8.57    9.43   9.43     9.43   1780240.0   
105  2300184  20170105   15.22     14.42   15.86  15.22    15.86   8958443.0   
0    2300588  20170105    5.93      4.94    7.11   5.93     7.11      9250.0   
189  2002156  20170105   11.65     11.38   12.08  11.52    11.56  18331538.0   

         d_amount  
179  7.747815e+08  
184  1.210156e+08  
234  4.351830e+08  
0    1.695004e+05  
241  1.664731e+08  
184  1.678766e+07  
105  1.392772e+08  
0    6.529950e+04  
189  2.160266e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
620   2002156  20170105   11.65       0.0   12.08  11.52    11.56  18331538   
629   2002165  20170105    9.43       0.0    9.43   9.43     9.43   1780240   
871   2002408  20170105   11.19       0.0   12.10  11.08    12.10  37026660   
927   2002464  20170105   78.03       0.0   78.82  71.00    71.30  10357751   
1186  2002727  20170105   21.66       0.0   21.88  20.84    20.95   7783685   
1469  2300184  20170105   15.22       0.0   15.86  15.22    15.86   8958443   
1761  2300480  20170105   24.44       0.0   24.44  23.80    24.44   4955837   
1857  2300587  20170105   18.62       0.0   20.32  18.62    20.32      8423   
1858  2300588  20170105    5.93       0.0    7.11   5.93     7.11      9250   

       d_amount  
620   216026573  
629    16787663  
871   435182997  
927   774781511  
1186  166473109  
1469  139277239  
1761  121015640  
1857     169500  
1858      65299

0:00:19.343954
no massive missing


array([2300588], dtype=int32)

0:01:50.009169


20170105

SZ finished
0:00:29.756775
0:02:33.279339
0:01:41.627678
1
2
3
4
0:03:35.619031


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
223  2002346  20170106   41.81     42.95   47.25  38.66    47.25  20286273.0   
0    2002838  20170106   18.34     15.28   22.00  18.34    22.00      7021.0   
148  2300047  20170106   19.00     19.90   19.89  17.91    17.91  23541811.0   
242  2002159  20170106   31.60     32.00   32.30  30.50    31.95   3430745.0   
0    2300583  20170106   48.35     40.29   58.02  48.35    58.02     14609.0   
202  2002659  20170106   19.60     21.77   20.27  19.59    19.59   6726175.0   
185  2300496  20170106   47.49     52.28   50.48  47.05    47.05  14668436.0   

         d_amount  
223  8.876573e+08  
0    1.540478e+05  
148  4.284397e+08  
242  1.070270e+08  
0    8.442322e+05  
202  1.320525e+08  
185  7.031823e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
623   2002159  20170106   31.60       0.0   32.30  30.50    31.95   3430745   
809   2002346  20170106   41.81       0.0   47.25  38.66    47.25  20286273   
1121  2002659  20170106   19.60       0.0   20.27  19.59    19.59   6726175   
1287  2002838  20170106   18.34       0.0   22.00  18.34    22.00      7021   
1334  2300047  20170106   19.00       0.0   19.89  17.91    17.91  23541811   
1778  2300496  20170106   47.49       0.0   50.48  47.05    47.05  14668436   
1856  2300583  20170106   48.35       0.0   58.02  48.35    58.02     14609   

       d_amount  
623   107026955  
809   887657269  
1121  132052549  
1287     154047  
1334  428439730  
1778  703182346  
1856     844232

0:00:17.912872
no massive missing


array([2300583, 2002838], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:48.042102


20170106

SZ finished
0:00:29.874359
0:01:52.529369
0:01:25.348266
1
2
3
4
0:03:34.862660


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
247  2002167  20170109   14.30     14.19   14.30  12.96    13.52  27767451.0   
63   2300323  20170109    8.65      8.99    9.78   8.09     8.97  34289604.0   
208  2002602  20170109   50.00     46.89   50.00  42.20    42.20   7890484.0   
161  2000531  20170109   11.80     11.47   12.62  11.77    12.62  15233684.0   
161  2000987  20170109   15.94     14.49   15.94  15.48    15.94  21207969.0   

         d_amount  
247  3.779358e+08  
63   3.110890e+08  
208  3.460113e+08  
161  1.882337e+08  
161  3.377982e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
125   2000531  20170109   11.80       0.0   12.62  11.77    12.62  15233684   
452   2000987  20170109   15.94       0.0   15.94  15.48    15.94  21207969   
631   2002167  20170109   14.30       0.0   14.30  12.96    13.52  27767451   
1064  2002602  20170109   50.00       0.0   50.00  42.20    42.20   7890484   
1608  2300323  20170109    8.65       0.0    9.78   8.09     8.97  34289604   

       d_amount  
125   188233697  
452   337798198  
631   377935780  
1064  346011301  
1608  311089041

0:00:16.918894
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:32.898871


20170109

SZ finished
0:00:34.577967
0:01:59.637939
0:01:41.262075
1
2
3
4
0:03:34.674421


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
0    2300591  20170110    3.98      3.07    4.42   3.98     4.42     13669.0   
0    2002840  20170110    7.86      6.55    9.43   7.86     9.43     12788.0   
166  2000953  20170110   16.06     16.70   18.37  15.80    18.37  14812041.0   
237  2000889  20170110   17.15     15.59   17.15  17.15    17.15   2675224.0   

         d_amount  
0    6.036706e+04  
0    1.203818e+05  
166  2.627864e+08  
237  4.588009e+07

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
376   2000889  20170110   17.15       0.0   17.15  17.15    17.15   2675224   
424   2000953  20170110   16.06       0.0   18.37  15.80    18.37  14812041   
1288  2002840  20170110    7.86       0.0    9.43   7.86     9.43     12788   
1862  2300591  20170110    3.98       0.0    4.42   3.98     4.42     13669   

       d_amount  
376    45880091  
424   262786414  
1288     120381  
1862      60367

0:00:17.043254
no massive missing


array([2300591, 2002840], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:44.458074


20170110

SZ finished
0:00:30.152101
0:02:21.132060
0:01:28.203384
1
2
3
4
0:03:24.209273


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
240  2000411  20170111   24.31     22.10   24.31  24.31    24.31    456377.0   
173  2300477  20170111   23.52     24.84   24.20  22.36    22.36  14336006.0   
0    2300590  20170111   34.18     28.48   41.01  34.18    41.01      7800.0   
0    2300580  20170111   12.49      9.59   13.81  12.49    13.81      9181.0   

         d_amount  
240  1.109452e+07  
173  3.281495e+08  
0    3.174900e+05  
0    1.266477e+05

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
82    2000411  20170111   24.31       0.0   24.31  24.31    24.31    456377   
1760  2300477  20170111   23.52       0.0   24.20  22.36    22.36  14336006   
1855  2300580  20170111   12.49       0.0   13.81  12.49    13.81      9181   
1863  2300590  20170111   34.18       0.0   41.01  34.18    41.01      7800   

       d_amount  
82     11094524  
1760  328149465  
1855     126647  
1863     317490

0:00:17.012800
no massive missing


array([2300580, 2300590], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
5
0:01:36.262835


20170111

SZ finished
0:00:42.316166
0:02:47.688578
0:01:26.089309
1
2
3
4
0:03:26.003907


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close     d_volume  \
211  2002151  20170112   31.00     31.90   35.09  30.00    33.27   30372659.0   
0    2300584  20170112   13.33     11.11   16.00  13.33    16.00       9100.0   
242  2000520  20170112    8.69      7.90    8.69   8.52     8.69  114371170.0   
155  2000932  20170112    6.40      6.07    6.49   5.63     5.65   95007106.0   
190  2000533  20170112   11.54     12.82   12.66  11.54    11.58   40667789.0   
0    2002824  20170112   11.76      9.80   14.11  11.76    14.11      14962.0   
194  2002440  20170112   15.22     16.34   15.96  14.71    15.04   23008039.0   
157  2000925  20170112   24.90     24.80   24.90  22.55    22.92    9668504.0   
181  2002462  20170112   38.98     42.53   40.89  38.28    38.33    8292314.0   

         d_amount  
211  1.023876e+09  
0    1.446630e+05  
242  9.934325e+08  
155  5.760865e+08  
190  4.819903e+08  
0    2.101690e+05  
194  3.501500e+08  
157  2.267081e+08  
181  3.234379e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close   d_volume  \
116   2000520  20170112    8.69       0.0    8.69   8.52     8.69  114371170   
127   2000533  20170112   11.54       0.0   12.66  11.54    11.58   40667789   
405   2000925  20170112   24.90       0.0   24.90  22.55    22.92    9668504   
412   2000932  20170112    6.40       0.0    6.49   5.63     5.65   95007106   
615   2002151  20170112   31.00       0.0   35.09  30.00    33.27   30372659   
903   2002440  20170112   15.22       0.0   15.96  14.71    15.04   23008039   
925   2002462  20170112   38.98       0.0   40.89  38.28    38.33    8292314   
1275  2002824  20170112   11.76       0.0   14.11  11.76    14.11      14962   
1860  2300584  20170112   13.33       0.0   16.00  13.33    16.00       9100   

        d_amount  
116    993432476  
127    481990345  
405    226708113  
412    576086456  
615   1023875622  
903    350150008  
925    323437901  
1275      210168  
1860      144663

0:00:16.610648
no massive missing


array([2300584, 2002824], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
3
0:01:32.412636


20170112

SZ finished
0:00:27.801699
0:01:55.753252
0:01:27.568301
1
2
3
4
0:03:31.586733


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close     d_volume  \
183  2002656  20170113   22.10     22.19   22.10  20.30    20.55    6596312.0   
24   2300537  20170113   43.91     48.79   44.68  43.91    43.91    1650400.0   
0    2300593  20170113    7.84      6.53    9.40   7.84     9.40      10700.0   
0    2300589  20170113    8.37      6.34    9.13   8.37     9.13       8068.0   
184  2002034  20170113   39.96     36.33   39.96  39.47    39.96    2427239.0   
130  2000002  20170113   21.00     20.40   22.40  20.90    21.81  106426641.0   

         d_amount  
183  1.397887e+08  
24   7.250531e+07  
0    9.905000e+04  
0    7.328084e+04  
184  9.697993e+07  
130  2.322229e+09

ID      date  d_open  d_yclose  d_high  d_low  d_close   d_volume  \
1     2000002  20170113   21.00       0.0   22.40  20.90    21.81  106426641   
498   2002034  20170113   39.96       0.0   39.96  39.47    39.96    2427239   
1118  2002656  20170113   22.10       0.0   22.10  20.30    20.55    6596312   
1818  2300537  20170113   43.91       0.0   44.68  43.91    43.91    1650400   
1865  2300589  20170113    8.37       0.0    9.13   8.37     9.13       8068   
1868  2300593  20170113    7.84       0.0    9.40   7.84     9.40      10700   

        d_amount  
1     2322228972  
498     96979934  
1118   139788718  
1818    72505307  
1865       73280  
1868       99050

0:00:17.234504
no massive missing


array([2300593], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
4
0:01:33.313917


20170113

SZ finished
0:00:29.747250
0:03:13.476196
0:01:36.802848
1
2
3
4
0:03:49.297937


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
118  2300104  20170116   36.88     35.80   38.98  33.95    35.40  96948774.0   
144  2000617  20170116   20.23     21.72   22.32  19.55    19.78  12632986.0   
244  2002045  20170116   12.45     12.45   12.45  11.21    11.50  25542048.0   
248  2300381  20170116   24.80     25.81   24.80  23.23    23.23   5877081.0   

         d_amount  
118  3.570631e+09  
144  2.606378e+08  
244  2.988662e+08  
248  1.395654e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
193   2000617  20170116   20.23       0.0   22.32  19.55    19.78  12632986   
509   2002045  20170116   12.45       0.0   12.45  11.21    11.50  25542048   
1392  2300104  20170116   36.88       0.0   38.98  33.95    35.40  96948774   
1666  2300381  20170116   24.80       0.0   24.80  23.23    23.23   5877081   

        d_amount  
193    260637756  
509    298866188  
1392  3570631330  
1666   139565374

0:00:18.875855
no massive missing


array([], dtype=int32)

0:01:46.051166


20170116

SZ finished
0:00:32.344729
0:02:18.482740
0:01:31.191175
1
2
3
4
0:03:35.592965


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
106  2002798  20170117   60.34     67.00   62.34  60.30    60.30   3956860.0   
252  2002130  20170117   13.35     14.31   13.82  13.22    13.68  12746153.0   
244  2000782  20170117   11.15     10.14   11.15  11.15    11.15   5642011.0   
0    2300595  20170117   28.57     23.81   34.29  28.57    34.29      8000.0   
246  2300207  20170117   12.24     13.60   12.24  12.24    12.24   7182300.0   

         d_amount  
106  2.390423e+08  
252  1.718570e+08  
244  6.290842e+07  
0    2.723180e+05  
246  8.791135e+07

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
305   2000782  20170117   11.15       0.0   11.15  11.15    11.15   5642011   
594   2002130  20170117   13.35       0.0   13.82  13.22    13.68  12746153   
1251  2002798  20170117   60.34       0.0   62.34  60.30    60.30   3956860   
1494  2300207  20170117   12.24       0.0   12.24  12.24    12.24   7182300   
1869  2300595  20170117   28.57       0.0   34.29  28.57    34.29      8000   

       d_amount  
305    62908422  
594   171856996  
1251  239042301  
1494   87911352  
1869     272318

0:00:19.181237
no massive missing


array([2300595], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:45.595197


20170117

SZ finished
0:00:33.030028
0:01:47.181043
0:01:25.786250
1
2
3
4
0:03:35.697355


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
200  2300054  20170118   20.49     21.41   21.01  19.66    20.49   6571799.0   
188  2000563  20170118    6.73      7.48    6.73   6.73     6.73  12127200.0   
253  2002300  20170118   17.64     17.29   19.02  16.23    19.01  96239189.0   
132  2300434  20170118   37.00     37.40   37.00  35.00    36.02   2682967.0   
246  2002318  20170118   10.10     10.20   10.10   9.50     9.99  15416472.0   

         d_amount  
200  1.334153e+08  
188  8.161606e+07  
253  1.734456e+09  
132  9.691627e+07  
246  1.525009e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
152   2000563  20170118    6.73       0.0    6.73   6.73     6.73  12127200   
762   2002300  20170118   17.64       0.0   19.02  16.23    19.01  96239189   
780   2002318  20170118   10.10       0.0   10.10   9.50     9.99  15416472   
1342  2300054  20170118   20.49       0.0   21.01  19.66    20.49   6571799   
1718  2300434  20170118   37.00       0.0   37.00  35.00    36.02   2682967   

        d_amount  
152     81616056  
762   1734455928  
780    152500853  
1342   133415331  
1718    96916266

0:00:16.218410
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
2
0:01:29.588249


20170118

SZ finished
0:00:26.499672
0:02:47.065931
0:01:25.237929
1
2
3
4
0:03:27.905605


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
0    2002842  20170119   13.70     11.42   16.44  13.70    16.44      9502.0   
128  2002591  20170119   15.66     16.73   16.10  15.06    15.06   8072456.0   
0    2300596  20170119   13.55     11.29   16.26  13.55    16.26     14213.0   
248  2002123  20170119   14.63     15.25   14.63  13.73    13.77  11639622.0   
131  2002377  20170119    9.25      9.18   10.00   8.63     9.73  40300111.0   
0    2002841  20170119   22.87     19.06   27.45  22.87    27.45     23300.0   

         d_amount  
0    1.559008e+05  
128  1.252265e+08  
0    2.294193e+05  
248  1.634239e+08  
131  3.766324e+08  
0    6.379820e+05

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
586   2002123  20170119   14.63       0.0   14.63  13.73    13.77  11639622   
839   2002377  20170119    9.25       0.0   10.00   8.63     9.73  40300111   
1052  2002591  20170119   15.66       0.0   16.10  15.06    15.06   8072456   
1289  2002841  20170119   22.87       0.0   27.45  22.87    27.45     23300   
1290  2002842  20170119   13.70       0.0   16.44  13.70    16.44      9502   
1871  2300596  20170119   13.55       0.0   16.26  13.55    16.26     14213   

       d_amount  
586   163423875  
839   376632434  
1052  125226496  
1289     637982  
1290     155900  
1871     229419

0:00:15.716629
no massive missing


array([2300596, 2002841, 2002842], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
4
0:01:31.658876


20170119

SZ finished
0:00:29.900225
0:03:57.647434
0:01:31.732833
1
2
3
4
0:03:32.049198


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close     d_volume  \
121  2300104  20170120   38.12     38.13   41.17  37.91    39.35   93145197.0   
225  2000750  20170120    6.27      6.97    6.54   6.27     6.43  240392274.0   
0    2300598  20170120   11.53      8.73   12.57  11.53    12.57      10000.0   
0    2002843  20170120    7.94      6.08    8.76   7.94     8.76      14401.0   
133  2002725  20170120   20.51     22.55   23.50  20.51    21.86    9465968.0   
0    2300592  20170120    6.25      5.21    7.50   6.25     7.50       8300.0   
235  2002694  20170120   35.00     35.20   38.20  31.71    36.80    4386916.0   

         d_amount  
121  3.700226e+09  
225  1.528556e+09  
0    1.251800e+05  
0    1.260678e+05  
133  2.012498e+08  
0    6.181500e+04  
235  1.540836e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close   d_volume  \
284   2000750  20170120    6.27       0.0    6.54   6.27     6.43  240392274   
1155  2002694  20170120   35.00       0.0   38.20  31.71    36.80    4386916   
1183  2002725  20170120   20.51       0.0   23.50  20.51    21.86    9465968   
1291  2002843  20170120    7.94       0.0    8.76   7.94     8.76      14401   
1394  2300104  20170120   38.12       0.0   41.17  37.91    39.35   93145197   
1870  2300592  20170120    6.25       0.0    7.50   6.25     7.50       8300   
1874  2300598  20170120   11.53       0.0   12.57  11.53    12.57      10000   

        d_amount  
284   1528555903  
1155   154083647  
1183   201249785  
1291      126067  
1394  3700226380  
1870       61815  
1874      125180

0:00:17.873972
no massive missing


array([2300592, 2002843], dtype=int32)

0:01:40.657850


20170120

SZ finished
0:00:30.098022
0:02:58.233992
0:01:25.603992
1
2
3
4
0:03:16.104552


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
212  2300098  20170123   14.26     15.84   14.26  14.26    14.26   4002400.0   
0    2300597  20170123    6.64      5.53    7.96   6.64     7.96     18386.0   
167  2002211  20170123   12.40     13.15   13.20  12.10    12.74  30734764.0   
143  2002617  20170123   15.60     14.63   15.60  14.38    14.61   7819670.0   
242  2000671  20170123    5.57      5.57    5.91   5.55     5.75  43464825.0   
211  2002286  20170123   16.50     17.74   19.40  16.45    17.09  21313301.0   
101  2000803  20170123   23.36     21.24   23.36  22.98    23.36   4195124.0   
0    2300599  20170123    8.45      7.04   10.14   8.45    10.14     27192.0   
248  2002086  20170123   11.88     12.20   11.88  10.98    11.51  11114572.0   
242  2000062  20170123   27.50     27.06   28.88  27.36    28.27   6310450.0   

         d_amount  
212  5.707422e+07  
0    1.453626e+05  
167  3.839836e+08  
143  1.154717e+08  
242  2.501317e+08  
211  3.646422e+08  
101  9.796565e+07  
0    2.727709e+05  
248  1.269208e+08  
242  1.783698e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
48    2000062  20170123   27.50       0.0   28.88  27.36    28.27   6310450   
228   2000671  20170123    5.57       0.0    5.91   5.55     5.75  43464825   
322   2000803  20170123   23.36       0.0   23.36  22.98    23.36   4195124   
549   2002086  20170123   11.88       0.0   11.88  10.98    11.51  11114572   
674   2002211  20170123   12.40       0.0   13.20  12.10    12.74  30734764   
748   2002286  20170123   16.50       0.0   19.40  16.45    17.09  21313301   
1078  2002617  20170123   15.60       0.0   15.60  14.38    14.61   7819670   
1388  2300098  20170123   14.26       0.0   14.26  14.26    14.26   4002400   
1874  2300597  20170123    6.64       0.0    7.96   6.64     7.96     18386   
1876  2300599  20170123    8.45       0.0   10.14   8.45    10.14     27192   

       d_amount  
48    178369789  
228   250131701  
322    97965654  
549   126920818  
674   383983579  
748   364642166  
1078  115471737  
1388   57074224  
1874     145362  
1876     272770

0:00:15.937630
no massive missing


array([2300597, 2300599], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:32.456695


20170123

SZ finished
0:00:27.882894
empty data
/mnt/SZ/SZCYB/TickAB/SZ/20170124/300198.csv
empty data
/mnt/SZ/SZCYB/TickAB/SZ/20170124/300199.csv
empty data
/mnt/SZ/SZCYB/TickAB/SZ/20170124/300200.csv
empty data
/mnt/SZ/SZCYB/TickAB/SZ/20170124/300201.csv
empty data
/mnt/SZ/SZCYB/TickAB/SZ/20170124/300202.csv
empty data
/mnt/SZ/SZCYB/TickAB/SZ/20170124/300203.csv
empty data
/mnt/SZ/SZCYB/TickAB/SZ/20170124/300204.csv
empty data
/mnt/SZ/SZCYB/TickAB/SZ/20170124/300205.csv
empty data
/mnt/SZ/SZCYB/TickAB/SZ/20170124/300206.csv
0:08:25.558176
0:01:17.549436
1
2
3
4
0:03:06.074995


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
259  2300205  20170124   13.85     13.85   13.85  13.50    13.55   5535217.0   
252  2000868  20170124    6.76      6.86    7.12   6.62     6.94  20201982.0   
259  2300202  20170124   19.95     19.94   19.99  19.40    19.46   4925474.0   
248  2000557  20170124    5.61      5.70    6.27   5.61     6.27  47321293.0   
259  2300206  20170124    8.31      8.36    8.38   8.16     8.19   4661792.0   
0    2002839  20170124    5.24      4.37    6.29   5.24     6.29    115553.0   
259  2300198  20170124    6.53      6.53    6.70   6.49     6.56  11046046.0   
259  2300199  20170124   16.40     16.38   16.51  16.12    16.19   5178721.0   
206  2300201  20170124    8.34      8.46    8.53   8.31     8.46   9503900.0   
219  2300200  20170124   16.47     16.58   16.94  16.47    16.78   1204545.0   
259  2300204  20170124   16.71     16.78   16.84  16.56    16.61   1344837.0   
259  2300203  20170124   30.05     30.15   30.17  29.40    29.50   4310109.0   
246  2002368  20170124   31.65     30.98   32.30  29.45    29.62  10337977.0   
162  2000585  20170124    8.37      7.61    8.37   8.37     8.37   4424756.0   
186  2000676  20170124   18.25     19.73   19.30  18.25    18.58  14520355.0   
258  2000666  20170124   22.50     22.38   22.67  21.97    22.14   3255936.0   

         d_amount  
259  7.534077e+07  
252  1.391843e+08  
259  9.671206e+07  
248  2.924698e+08  
259  3.826475e+07  
0    7.250124e+05  
259  7.246232e+07  
259  8.442837e+07  
206  8.014396e+07  
219  2.022490e+07  
259  2.238076e+07  
259  1.279956e+08  
246  3.154341e+08  
162  3.703521e+07  
186  2.732345e+08  
258  7.231947e+07

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
147   2000557  20170124    5.61       0.0    6.27   5.61     6.27  47321293   
166   2000585  20170124    8.37       0.0    8.37   8.37     8.37   4424756   
223   2000666  20170124   22.50       0.0   22.67  21.97    22.14   3255936   
231   2000676  20170124   18.25       0.0   19.30  18.25    18.58  14520355   
361   2000868  20170124    6.76       0.0    7.12   6.62     6.94  20201982   
830   2002368  20170124   31.65       0.0   32.30  29.45    29.62  10337977   
1288  2002839  20170124    5.24       0.0    6.29   5.24     6.29    115553   

       d_amount  
147   292469765  
166    37035207  
223    72319474  
231   273234506  
361   139184251  
830   315434115  
1288     725012

0:00:15.431882
no massive missing


array([2002839], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
4
0:01:29.529757


20170124

SZ finished
0:00:40.861671
0:01:52.017432
0:01:29.644715
1
2
3
4
0:03:08.033571


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
253  2300394  20170125   29.02     30.43   31.28  29.02    30.31   1869534.0   
253  2002340  20170125    6.10      5.97    6.37   6.06     6.22  40845603.0   
0    2300600  20170125   18.13     13.73   19.77  18.13    19.77      6338.0   
251  2300409  20170125   32.00     31.37   34.51  32.00    33.06   3298380.0   
0    2002845  20170125   21.11     15.99   23.03  21.11    23.03     14235.0   
185  2300459  20170125   15.49     17.21   16.49  15.49    15.49  39216173.0   
227  2300468  20170125   51.00     50.17   52.74  50.80    51.43   1125031.0   
0    2300578  20170125   11.64      9.70   13.97  11.64    13.97      5701.0   
204  2300100  20170125   30.60     34.00   30.60  30.60    30.60    985900.0   

        d_amount  
253   56308683.0  
253  255190480.0  
0       125138.0  
251  110618451.0  
0       326872.0  
185  619523469.0  
227   58080792.0  
0        78229.0  
204   30168540.0

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
802   2002340  20170125    6.10       0.0    6.37   6.06     6.22  40845603   
1293  2002845  20170125   21.11       0.0   23.03  21.11    23.03     14235   
1392  2300100  20170125   30.60       0.0   30.60  30.60    30.60    985900   
1683  2300394  20170125   29.02       0.0   31.28  29.02    30.31   1869534   
1698  2300409  20170125   32.00       0.0   34.51  32.00    33.06   3298380   
1747  2300459  20170125   15.49       0.0   16.49  15.49    15.49  39216173   
1756  2300468  20170125   51.00       0.0   52.74  50.80    51.43   1125031   
1859  2300578  20170125   11.64       0.0   13.97  11.64    13.97      5701   
1880  2300600  20170125   18.13       0.0   19.77  18.13    19.77      6338   

       d_amount  
802   255190480  
1293     326872  
1392   30168540  
1683   56308682  
1698  110618450  
1747  619523468  
1756   58080791  
1859      78228  
1880     125138

0:00:15.646123
no massive missing


array([2300578, 2300596], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
4
0:01:26.737787


20170125

SZ finished
0:00:25.442900
0:01:48.720558
0:01:16.312531
1
2
3
4
0:02:52.584969


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
0    2300602  20170126   17.78     14.82   21.34  17.78    21.34      9200.0   
0    2300603  20170126    5.46      4.55    6.55   5.46     6.55      6400.0   
256  2002388  20170126   17.01     16.62   17.15  14.98    15.30  97868912.0   
236  2000166  20170126    6.29      6.25    6.35   6.25     6.31  92589004.0   

         d_amount  
0    1.915220e+05  
0    4.154100e+04  
256  1.556168e+09  
236  5.826766e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
69    2000166  20170126    6.29       0.0    6.35   6.25     6.31  92589004   
850   2002388  20170126   17.01       0.0   17.15  14.98    15.30  97868912   
1881  2300602  20170126   17.78       0.0   21.34  17.78    21.34      9200   
1882  2300603  20170126    5.46       0.0    6.55   5.46     6.55      6400   

        d_amount  
69     582676602  
850   1556168341  
1881      191522  
1882       41541

0:00:14.696254
no massive missing


array([2300602, 2300603], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
6
0:01:22.994337


20170126

SZ finished
0:00:26.099363
0:02:05.649427
0:01:12.639351
1
2
3
4
0:02:47.816595


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


Empty DataFrame
Columns: [ID, date, d_open, d_yclose, d_high, d_low, d_close, d_volume, d_amount]
Index: []

Empty DataFrame
Columns: [ID, date, d_open, d_yclose, d_high, d_low, d_close, d_volume, d_amount]
Index: []

/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:316: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Attention!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0:00:02.469383
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
5
0:01:19.745128


20170203

SZ finished
0:00:32.349088
0:02:10.979228
0:01:35.694115
1
2
3
4
0:03:18.616892


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
212  2300005  20170206   15.02     16.69   15.45  15.02    15.06  42716510.0   
260  2000885  20170206   27.20     28.93   31.82  26.04    31.82  47564027.0   
256  2002628  20170206    8.67      8.64    8.69   8.30     8.53   5052321.0   

         d_amount  
212  6.435381e+08  
260  1.294182e+09  
256  4.284754e+07

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
371   2000885  20170206   27.20       0.0   31.82  26.04    31.82  47564027   
1089  2002628  20170206    8.67       0.0    8.69   8.30     8.53   5052321   
1298  2300005  20170206   15.02       0.0   15.45  15.02    15.06  42716510   

        d_amount  
371   1294182044  
1089    42847543  
1298   643538083

0:00:16.880173
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:35.706689


20170206

SZ finished
0:00:39.292785
0:02:03.477614
0:01:37.374275
1
2
3
4
0:03:19.834894


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
246  2002562  20170207   13.00     12.01   13.00  12.46    12.50  22465192.0   
0    2300601  20170207    4.35      3.29    4.74   4.35     4.74     11600.0   
184  2002239  20170207   14.12     15.69   17.26  14.12    16.69  78000512.0   
254  2300030  20170207   13.84     12.58   13.84  13.04    13.14  18171765.0   
122  2300179  20170207    8.08      7.70    8.47   8.08     8.47  34902527.0   
0    2002846  20170207   10.00      8.33   12.00  10.00    12.00     11907.0   

         d_amount  
246  2.836555e+08  
0    5.475500e+04  
184  1.126757e+09  
254  2.454650e+08  
122  2.943338e+08  
0    1.421840e+05

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
702   2002239  20170207   14.12       0.0   17.26  14.12    16.69  78000512   
1023  2002562  20170207   13.00       0.0   13.00  12.46    12.50  22465192   
1294  2002846  20170207   10.00       0.0   12.00  10.00    12.00     11907   
1324  2300030  20170207   13.84       0.0   13.84  13.04    13.14  18171765   
1472  2300179  20170207    8.08       0.0    8.47   8.08     8.47  34902527   
1882  2300601  20170207    4.35       0.0    4.74   4.35     4.74     11600   

        d_amount  
702   1126756611  
1023   283655467  
1294      142184  
1324   245465040  
1472   294333798  
1882       54755

0:00:16.768121
no massive missing


array([2002846], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
4
0:01:45.094314


20170207

SZ finished
0:00:35.331733
0:02:02.965611
0:01:26.070961
1
2
3
4
0:03:24.609021


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
183  2000670  20170208    7.65      7.96    7.77   7.56     7.60  32144171.0   
0    2300606  20170208   10.03      8.36   12.04  10.03    12.04      4200.0   
122  2300450  20170208   33.00     33.99   36.70  32.05    35.46  21308219.0   
205  2002635  20170208   33.50     36.40   37.94  33.50    36.32  28746097.0   
0    2300605  20170208   11.28      9.40   13.54  11.28    13.54      5517.0   
0    2002847  20170208   11.95      9.14   13.16  11.95    13.16     13740.0   

         d_amount  
183  2.443920e+08  
0    5.026600e+04  
122  7.425306e+08  
205  1.042526e+09  
0    7.467933e+04  
0    1.806964e+05

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
227   2000670  20170208    7.65       0.0    7.77   7.56     7.60  32144171   
1096  2002635  20170208   33.50       0.0   37.94  33.50    36.32  28746097   
1295  2002847  20170208   11.95       0.0   13.16  11.95    13.16     13740   
1741  2300450  20170208   33.00       0.0   36.70  32.05    35.46  21308219   
1886  2300605  20170208   11.28       0.0   13.54  11.28    13.54      5517   
1887  2300606  20170208   10.03       0.0   12.04  10.03    12.04      4200   

        d_amount  
227    244391996  
1096  1042526072  
1295      180696  
1741   742530571  
1886       74679  
1887       50266

0:00:16.717068
no massive missing


array([2300605, 2300606, 2002847], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
2
0:01:33.222665


20170208

SZ finished
0:00:38.251967
0:01:58.033625
0:01:44.622498
1
2
3
4
0:03:42.578693


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
0  2300607  20170209   24.74     18.74   26.99  24.74    26.99    5300.0   

   d_amount  
0  142372.0

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
1888  2300607  20170209   24.74       0.0   26.99  24.74    26.99      5300   

      d_amount  
1888    142372

0:00:18.141453
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:49.634875


20170209

SZ finished
0:00:41.896686
0:01:57.083119
0:01:31.454303
1
2
3
4
0:03:38.641802


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
200  2300473  20170210   71.00     78.12   73.25  70.31    70.31   4185791.0   
258  2002036  20170210   18.66     17.87   19.23  18.10    18.18  14420171.0   
259  2002748  20170210   27.25     27.50   28.50  25.41    25.63  43266749.0   

         d_amount  
200  2.963670e+08  
258  2.667745e+08  
259  1.163903e+09

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
499   2002036  20170210   18.66       0.0   19.23  18.10    18.18  14420171   
1205  2002748  20170210   27.25       0.0   28.50  25.41    25.63  43266749   
1763  2300473  20170210   71.00       0.0   73.25  70.31    70.31   4185791   

        d_amount  
499    266774481  
1205  1163902729  
1763   296367037

0:00:18.149403
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:39.956026


20170210

SZ finished
0:00:34.240193
0:01:56.953062
0:01:42.348555
1
2
3
4
0:03:41.474841


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
0    2300608  20170213   19.39     16.16   23.27  19.39    23.27      4610.0   
257  2002417  20170213   15.83     15.54   17.09  15.83    16.42  14544809.0   
0    2300610  20170213   13.95     10.57   15.22  13.95    15.22      6594.0   
0    2002848  20170213    7.57      6.31    9.09   7.57     9.09     11901.0   

         d_amount  
0    1.031399e+05  
257  2.425509e+08  
0    9.972568e+04  
0    1.072572e+05

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
879   2002417  20170213   15.83       0.0   17.09  15.83    16.42  14544809   
1296  2002848  20170213    7.57       0.0    9.09   7.57     9.09     11901   
1890  2300608  20170213   19.39       0.0   23.27  19.39    23.27      4610   
1891  2300610  20170213   13.95       0.0   15.22  13.95    15.22      6594   

       d_amount  
879   242550947  
1296     107257  
1890     103139  
1891      99725

0:00:17.925115
no massive missing


array([2300010, 2300608, 2002848], dtype=int32)

0:01:47.621516


20170213

SZ finished
0:00:28.671873
0:02:07.452655
0:01:25.162099
1
2
3
4
0:03:21.489332


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


Empty DataFrame
Columns: [ID, date, d_open, d_yclose, d_high, d_low, d_close, d_volume, d_amount]
Index: []

Empty DataFrame
Columns: [ID, date, d_open, d_yclose, d_high, d_low, d_close, d_volume, d_amount]
Index: []

/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:316: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Attention!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0:00:02.870052
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
4
0:01:36.554569


20170214

SZ finished
0:00:38.877614
0:02:16.829431
0:01:30.101457
1
2
3
4
0:03:38.071935


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close     d_volume  \
212  2000727  20170215    3.47      3.37    3.58   3.38     3.41  209927903.0   
0    2300609  20170215    9.74      8.12   11.69   9.74    11.69       5545.0   
173  2300123  20170215   16.59     15.08   16.59  16.59    16.59     114691.0   
0    2300612  20170215   19.37     16.14   23.24  19.37    23.24       4900.0   
203  2000887  20170215   23.99     25.94   24.75  23.35    23.80   48776433.0   
260  2300408  20170215   18.00     17.15   18.87  17.75    17.90   40444554.0   
260  2300115  20170215   27.00     25.60   27.50  25.96    26.19   12987707.0   
80   2002809  20170215   68.02     74.08   72.80  68.02    68.80    4056578.0   
0    2300615  20170215   17.24     14.37   20.69  17.24    20.69       5200.0   

         d_amount  
212  7.206154e+08  
0    6.461998e+04  
173  1.902724e+06  
0    1.116490e+05  
203  1.172468e+09  
260  7.418283e+08  
260  3.468240e+08  
80   2.837421e+08  
0    1.039630e+05

ID      date  d_open  d_yclose  d_high  d_low  d_close   d_volume  \
273   2000727  20170215    3.47       0.0    3.58   3.38     3.41  209927903   
373   2000887  20170215   23.99       0.0   24.75  23.35    23.80   48776433   
1260  2002809  20170215   68.02       0.0   72.80  68.02    68.80    4056578   
1410  2300115  20170215   27.00       0.0   27.50  25.96    26.19   12987707   
1418  2300123  20170215   16.59       0.0   16.59  16.59    16.59     114691   
1700  2300408  20170215   18.00       0.0   18.87  17.75    17.90   40444554   
1891  2300609  20170215    9.74       0.0   11.69   9.74    11.69       5545   
1893  2300612  20170215   19.37       0.0   23.24  19.37    23.24       4900   
1894  2300615  20170215   17.24       0.0   20.69  17.24    20.69       5200   

        d_amount  
273    720615443  
373   1172467760  
1260   283742105  
1410   346824049  
1418     1902723  
1700   741828335  
1891       64619  
1893      111649  
1894      103963

0:00:17.415390
no massive missing


array([2300609, 2300612, 2300615], dtype=int32)

0:01:38.468555


20170215

SZ finished
0:00:29.215378
0:01:58.793112
0:01:28.052567
1
2
3
4
0:03:27.820546


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
257  2002092  20170216   14.00     12.98   14.00  13.32    13.60  95655859.0   
255  2002692  20170216   13.10     11.93   13.12  12.30    12.45  10994648.0   
198  2300310  20170216   23.96     22.76   23.96  22.22    22.65  13811349.0   
268  2300348  20170216   24.34     24.32   25.32  24.31    24.38   6404586.0   

         d_amount  
257  1.303883e+09  
255  1.389019e+08  
198  3.188581e+08  
268  1.585973e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
555   2002092  20170216   14.00       0.0   14.00  13.32    13.60  95655859   
1153  2002692  20170216   13.10       0.0   13.12  12.30    12.45  10994648   
1604  2300310  20170216   23.96       0.0   23.96  22.22    22.65  13811349   
1642  2300348  20170216   24.34       0.0   25.32  24.31    24.38   6404586   

        d_amount  
555   1303882774  
1153   138901923  
1604   318858071  
1642   158597290

0:00:17.166625
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
2
0:01:35.719770


20170216

SZ finished
0:00:27.098669
0:02:01.984524
0:01:32.473598
1
2
3
4
0:03:40.772996


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
238  2002346  20170217   36.01     36.38   40.02  36.01    40.02  30561330.0   
199  2300213  20170217   25.48     28.00   26.84  25.20    25.20  15899512.0   
255  2000807  20170217    7.40      6.73    7.40   7.40     7.40   4057474.0   
60   2300561  20170217   86.02     87.33   86.88  78.60    78.60   4856425.0   
184  2002629  20170217   12.31     13.11   12.90  11.80    11.80  34303183.0   
0    2002849  20170217   14.50     12.08   17.40  14.50    17.40     10675.0   

         d_amount  
238  1.192321e+09  
199  4.026429e+08  
255  3.002531e+07  
60   3.931191e+08  
184  4.110665e+08  
0    1.847300e+05

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
324   2000807  20170217    7.40      0.00    7.40   7.40     7.40   4057474   
808   2002346  20170217   36.01      0.00   40.02  36.01    40.02  30561330   
1090  2002629  20170217   12.31      0.00   12.90  11.80    11.80  34303183   
1297  2002849  20170217   14.50      0.00   17.40  14.50    17.40     10675   
1508  2300213  20170217   25.48      0.00   26.84  25.20    25.20  15899512   
1848  2300561  20170217   86.02    131.35   86.88  78.60    78.60   4856425   

        d_amount  
324     30025307  
808   1192321314  
1090   411066475  
1297      184730  
1508   402642858  
1848   393119071

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Attention!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0:00:03.220751
no massive missing


array([2002849], dtype=int32)

0:01:43.902260


20170217

SZ finished
0:00:37.871784
0:02:10.982400
0:01:31.610919
1
2
3
4
0:03:50.332606


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
0    2300613  20170220   66.77     55.64   80.12  66.77    80.12      5004.0   
0    2300611  20170220   14.36     11.97   17.24  14.36    17.24      6100.0   
263  2002628  20170220    8.82      8.71    8.95   8.73     8.92  18878782.0   

         d_amount  
0    3.982515e+05  
0    1.041560e+05  
263  1.676130e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
1089  2002628  20170220    8.82       0.0    8.95   8.73     8.92  18878782   
1894  2300611  20170220   14.36       0.0   17.24  14.36    17.24      6100   
1896  2300613  20170220   66.77       0.0   80.12  66.77    80.12      5004   

       d_amount  
1089  167613023  
1894     104156  
1896     398251

0:00:18.231299
no massive missing


array([2300611, 2300613], dtype=int32)

0:01:36.082218


20170220

SZ finished
0:00:41.136807
0:02:00.532772
0:01:33.376828
1
2
3
4
0:03:48.929417


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
248  2300268  20170221   36.00     35.37   38.00  32.16    34.51  15270443.0   
273  2002407  20170221   27.12     26.86   28.19  27.12    27.91  30025095.0   
171  2002396  20170221   18.35     19.70   19.43  18.03    19.01  30644408.0   
273  2002004  20170221    8.53      8.47    8.63   8.52     8.58  16372554.0   
193  2002347  20170221    9.58      9.98   10.80   9.51    10.44  39899988.0   
267  2002157  20170221    6.45      6.63    6.61   6.41     6.53  46523037.0   

         d_amount  
248  5.438722e+08  
273  8.356025e+08  
171  5.738486e+08  
273  1.402621e+08  
193  4.051766e+08  
267  3.019183e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
467   2002004  20170221    8.53       0.0    8.63   8.52     8.58  16372554   
620   2002157  20170221    6.45       0.0    6.61   6.41     6.53  46523037   
809   2002347  20170221    9.58       0.0   10.80   9.51    10.44  39899988   
858   2002396  20170221   18.35       0.0   19.43  18.03    19.01  30644408   
869   2002407  20170221   27.12       0.0   28.19  27.12    27.91  30025095   
1563  2300268  20170221   36.00       0.0   38.00  32.16    34.51  15270443   

       d_amount  
467   140262116  
620   301918294  
809   405176609  
858   573848605  
869   835602466  
1563  543872242

0:00:18.261539
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:40.499038


20170221

SZ finished
0:00:35.464768
0:02:02.002815
0:01:46.354769
1
2
3
4
0:03:43.466256


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
270  2300418  20170222   21.59     20.67    22.2   21.3     21.3  18152790.0   

         d_amount  
270  3.925948e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
1711  2300418  20170222   21.59       0.0    22.2   21.3     21.3  18152790   

       d_amount  
1711  392594782

0:00:18.208928
no massive missing


array([], dtype=int32)

0:01:41.854495


20170222

SZ finished
0:00:32.569460
0:02:12.493614
0:01:34.152631
1
2
3
4
0:03:48.652076


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close     d_volume  \
270  2000926  20170223   12.42     12.25   12.88  12.40    12.54   49496199.0   
206  2000563  20170223    6.39      6.47    6.39   6.16     6.19  117068624.0   
270  2000735  20170223    7.33      7.20    7.45   7.17     7.24   29981380.0   
201  2000635  20170223   32.50     30.17   32.50  29.78    29.88   32352789.0   
236  2300045  20170223   14.80     14.08   15.17  14.41    14.48   10790389.0   
270  2000663  20170223   15.00     15.44   16.98  14.87    16.98   22104562.0   
238  2002771  20170223   68.10     64.26   69.88  66.88    67.10    1372362.0   

         d_amount  
270  6.239379e+08  
206  7.283975e+08  
270  2.187059e+08  
201  1.008454e+09  
236  1.588878e+08  
270  3.598389e+08  
238  9.293955e+07

ID      date  d_open  d_yclose  d_high  d_low  d_close   d_volume  \
152   2000563  20170223    6.39       0.0    6.39   6.16     6.19  117068624   
207   2000635  20170223   32.50       0.0   32.50  29.78    29.88   32352789   
221   2000663  20170223   15.00       0.0   16.98  14.87    16.98   22104562   
279   2000735  20170223    7.33       0.0    7.45   7.17     7.24   29981380   
405   2000926  20170223   12.42       0.0   12.88  12.40    12.54   49496199   
1226  2002771  20170223   68.10       0.0   69.88  66.88    67.10    1372362   
1342  2300045  20170223   14.80       0.0   15.17  14.41    14.48   10790389   

        d_amount  
152    728397540  
207   1008453868  
221    359838945  
279    218705922  
405    623937867  
1226    92939553  
1342   158887796

0:00:18.354803
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:41.920944


20170223

SZ finished
0:00:28.643532
0:02:18.482372
0:01:32.660319
1
2
3
4
0:03:45.547073


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
101  2300513  20170224   86.18     95.36   91.00  85.82    85.82   4231091.0   
164  2300028  20170224   14.01     14.18   15.60  14.00    15.60  38308314.0   
154  2002555  20170224   19.64     18.18   20.00  18.95    19.61  39986001.0   
208  2300449  20170224   43.88     48.44   45.88  43.60    43.60   4080194.0   

         d_amount  
101  3.653572e+08  
164  5.846319e+08  
154  7.861933e+08  
208  1.784799e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
1016  2002555  20170224   19.64       0.0   20.00  18.95    19.61  39986001   
1325  2300028  20170224   14.01       0.0   15.60  14.00    15.60  38308314   
1742  2300449  20170224   43.88       0.0   45.88  43.60    43.60   4080194   
1804  2300513  20170224   86.18       0.0   91.00  85.82    85.82   4231091   

       d_amount  
1016  786193330  
1325  584631866  
1742  178479925  
1804  365357202

0:00:19.785222
no massive missing


array([], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
2
0:01:41.502551


20170224

SZ finished
0:00:34.575023
0:02:18.815616
0:01:36.654058
1
2
3
4
0:04:04.000226


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
238  2300457  20170227   66.11     66.46   69.35  66.11    67.87   1364219.0   
244  2000690  20170227   10.20      9.27   10.20   9.41     9.64  71586670.0   

         d_amount  
238  9.249704e+07  
244  6.996488e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
243   2000690  20170227   10.20       0.0   10.20   9.41     9.64  71586670   
1749  2300457  20170227   66.11       0.0   69.35  66.11    67.87   1364219   

       d_amount  
243   699648750  
1749   92497042

0:00:22.379580
no massive missing


array([], dtype=int32)

0:01:46.261835


20170227

SZ finished
0:00:36.484142
0:02:14.751932
0:01:34.054986
1
2
3
4
0:03:43.935075


/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:296: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/work516/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:297: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


ID      date  d_open  d_yclose  d_high  d_low  d_close    d_volume  \
121  2002798  20170228   55.01     52.56   57.80  53.52    55.30   2681337.0   
171  2300189  20170228    5.34      5.25    5.76   5.02     5.43  78781329.0   
0    2300617  20170228   29.26     24.38   35.11  29.26    35.11      3300.0   
138  2300046  20170228   23.98     23.81   25.00  23.85    24.17   2763178.0   
137  2002571  20170228   15.44     15.33   16.86  14.61    16.86  20809684.0   
241  2000657  20170228   14.25     14.31   15.74  14.21    15.74  41625508.0   

         d_amount  
121  1.496811e+08  
171  4.196102e+08  
0    1.138180e+05  
138  6.734337e+07  
137  3.281228e+08  
241  6.441338e+08

ID      date  d_open  d_yclose  d_high  d_low  d_close  d_volume  \
217   2000657  20170228   14.25       0.0   15.74  14.21    15.74  41625508   
1032  2002571  20170228   15.44       0.0   16.86  14.61    16.86  20809684   
1250  2002798  20170228   55.01       0.0   57.80  53.52    55.30   2681337   
1343  2300046  20170228   23.98       0.0   25.00  23.85    24.17   2763178   
1484  2300189  20170228    5.34       0.0    5.76   5.02     5.43  78781329   
1898  2300617  20170228   29.26       0.0   35.11  29.26    35.11      3300   

       d_amount  
217   644133750  
1032  328122771  
1250  149681147  
1343   67343369  
1484  419610214  
1898     113818

0:00:17.813268
no massive missing


array([2300617], dtype=int32)

has missing!!!!!!!!!!!!!!!!!!!!!!!
1
0:01:41.693671


20170228

SZ finished
0:00:36.671988
        ID      date  d_open  d_high  d_low  d_close_x  d_yclose  \
0  2002059  20170103   11.97   12.25   11.7      12.08     11.95   
1  2002059  20170103   11.97   12.25   11.7        NaN     11.97   
2  2300561  20170217   86.02   86.88   78.6      78.60     87.33   
3  2300561  20170217   86.02   86.88   78.6        NaN    131.35   

   d_cumprodCAA  d_dayReturn  d_5dayReturn  d_ICDayReturn  d_CSIDayReturn  \
0      0.998329     0.010879      0.005001       0.009122        0.008748   
1           NaN          NaN           NaN            NaN             NaN   
2      0.664865    -0.099966     -0.004467      -0.008204       -0.008710   
3           NaN          NaN           NaN            NaN             NaN   

     d_volume    d_amount_x    TORate  allZT  hasZT  isZT  allDT  hasDT  isDT  \
0  12013616.0  1.442012e+08  0.017680    0.0    0.0   0.0    0.0    0.0   0.0   
1  12013616.0           NaN       NaN    NaN    NaN   NaN    NaN    NaN   NaN   
2  